### ISSUE TITLE
Cannot load any provided map

### ISSUE THREAD

**Issue by imrodriguezro** [isl-org/DirectFuturePrediction#3]
Hi,

first of all, thanks for releasing the code!

Now regarding my issue, I cannot load any map in maps/ using set_doom_scenario_path. When I try it, it loads instead the first map of freedoom2.wad. If I try to open, let's say D1_basic.wad, with Slade, I get the error: Error opening D1_basic.wad: Unsupported or invalid Archive format.

Are the maps corrupted somehow? or do you avoid the issue in another way?

Thanks in advance!

**Comment by dosovits** [comment]
Hi,

Sorry, I am super busy now, but at some point I tried cloning the repo and the maps worked for me, and they seem to work for others. Have you tried re-downloading? Does the problem persist? Can you run vizdoom binary smth like 
./vizdoom -iwad PATH_TO_FREEDOOm/freedoom2.wad -file PATH_TO_MAPS/D1_basic.wad -warp 1 
?
I may be able to test in a few days.

Alexey

**Comment by imrodriguezro** [comment]
It's a bit embarrassing but also very odd. Chrome allows to download the html related to the map with 'wad' extension when one right-clicks on the file, so I was effectively trying to load the html to the game. Downloading the raw file solves the issue.

Thanks.
